// svelte/src/components/Sidebar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import type { TopicType } from '../types/TopicType';

	export let topics: TopicType[];

	// auto-subscribe to page
	$: currentPath = $page.url.pathname;
</script>

<nav class="navbar">
	<ul>
		{#each topics as topic}
			<li>
				<a
					href={`/topic/${topic.id}`}
					class="topic-link"
					class:active={$page.url.pathname === `/topic/${topic.id}`}
				>
					{topic.title}
				</a>
			</li>
		{/each}
	</ul>
</nav>

// vue/src/components/Sidebar.vue
<script setup lang="ts">
import type { TopicType } from "../types/TopicType";
defineProps<{ topics: TopicType[] }>();
</script>

<template>
  <nav class="navbar">
    <ul>
      <li v-for="topic in topics">
        <router-link
          :key="topic.id"
          :to="`/topic/${topic.id}`"
          class="topic-link"
          active-class="active"
        >
          {{ topic.title }}
        </router-link>
      </li>
    </ul>
  </nav>
</template>

<style scoped></style>
