// vue/src/components/Sidebar.vue
<script setup lang="ts">
import type { TopicType } from "../types/TopicType";
defineProps<{ topics: TopicType[] }>();
</script>

<template>
  <nav class="navbar">
    <ul>
      <li v-for="topic in topics">
        <router-link
          :key="topic.id"
          :to="`/topic/${topic.id}`"
          class="topic-link"
          active-class="active"
        >
          {{ topic.title }}
        </router-link>
      </li>
    </ul>
  </nav>
</template>

<style scoped></style>

// react/src/components/Sidebar.tsx
import { TopicType } from "../types/TopicType";
import TopicLink from "./TopicLink";
function Sidebar({ topics }: { topics: TopicType[] }) {
  return (
    <nav className="navbar">
      <ul>
        {topics.map((topic) => (
          <TopicLink topic={topic} />
        ))}
      </ul>
    </nav>
  );
}

export default Sidebar;
